---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCaauGJ5zB8yasjwQqtxZaLnuGGvY3Vh+NHWqXvvmEnokirv5g2R2sBr0ABUaPJIO+OtghxWUCmDCVor37tP1XNuIu9yuA9AJCRn3yvFdQ+2E1hj1VBm/bUj3Qiqizn1iY5ZImrp9GIBgGwl4fVfJiTenhJqd2DETJkHUz3Oq6Jdd/WpuTA/p8ujj6V0nftGwK1lR8lDM3gi/enEl7AaGtYLPHrR/30+b5ehI7I18e+EyMwE8C9vjg5O2YNCW2CWEOEX7QtGGXY44uHPa2CQSy/EICsK0dv2BiG0RpSxr55N9R+qPLOU09Wyhsiw2c9LQ8vN1BRIbzrUi6ydqApPlu3+KpIm34qfc+JgccmRSjc/Lo/UIlCvcOsx0CXhSmQCCe2Oxnb2x1gGjLDfy3I3ZL7TYSin5ZWEw3NWSdpzlEK7whGDiri8g+msDgURDaYjkGuJHciAvcgNMFVZX5s8WJFwxE0yKZ1FGdkFbVy3OaWWyi3kgEVE6Vk5pChhy3kGIyN22B0Co/KsNXlumulRyHjKqb3cHxBI9a3ekHjYMvMzRFTnPfkYMZc1n0km9j0eOEaL/6hhrsMqCvx0bvxRDV99XmX0e/OeqDbGxws2lgSwzTxXnPNYQ8oRN8qWMdPRMvU2oRLCfrILaTSwLDYRUQnpvqE02jgsot8rLBlOBW9698k9YnS1wLIXoeEF3D+fimB97usSA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: grafana-admin
      namespace: monitoring
    type: Opaque
